lib/rentit_web/router.ex
defmodule RentitWeb.Router do
  use RentitWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RentitWeb do
    pipe_through :browser # Use the default browser stack

    # get "/", PageController, :index
    resources "/", PlantController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RentitWeb do
  #   pipe_through :api
  # end
end

lib/rentit/application.ex
defmodule Rentit.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Rentit.Repo, []),
      # Start the endpoint when the application starts
      supervisor(RentitWeb.Endpoint, []),
      # Start your own worker by calling: Rentit.Worker.start_link(arg1, arg2, arg3)
      # worker(Rentit.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Rentit.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    RentitWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/rentit/plant.ex
defmodule Rentit.Plant do
  use Ecto.Schema
  import Ecto.Changeset


  schema "plants" do
    field :description, :string
    field :name, :string
    field :startdate, :string
    field :enddate, :string
    field :price, :string

    timestamps()
  end

  @doc false
  def changeset(plant, attrs) do
    plant
    |> cast(attrs, [:name, :description, :price, :startdate, :enddate])
    |> validate_required([:name, :description, :price, :startdate, :enddate])
  end
end

lib/rentit/repo.ex
defmodule Rentit.Repo do
  use Ecto.Repo, otp_app: :rentit

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/rentit_web/controllers/page_controller.ex
defmodule RentitWeb.PageController do
  use RentitWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/rentit_web/controllers/plant_controller.ex
defmodule RentitWeb.PlantController do
  use RentitWeb, :controller
  import Ecto.Query, only: [from: 2]

  alias Rentit.Repo
  alias Rentit.Plant

  def index(conn, _params) do
    changeset = Plant.changeset(%Plant{}, %{})
    render conn, "index.html", changeset: changeset
  end

  def create(conn, %{"plant" => plant_params}) do
    # IO.inspect plant_params["name"]
    if String.equivalent?(plant_params["name"], "") do
      changeset = Plant.changeset(%Plant{}, %{})
      # put_flash(conn, :info, "User created successfully.") 
      render conn, "index.html", changeset: changeset
    else
      name = plant_params["name"]
      query = from t in Plant,
              where: t.name == ^name

      plants = Repo.all(query)
      # put_flash(conn, :info, "User created successfully.") 
      render(conn, "update.html", plants: plants)


      
    end

  end



  def show(conn, %{"id" => id}) do
    plant = Repo.get!(Plant, id)
    render(conn, "show.html", plant: plant)
  end
end

lib/rentit_web/views/error_view.ex
defmodule RentitWeb.ErrorView do
  use RentitWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/rentit_web/views/layout_view.ex
defmodule RentitWeb.LayoutView do
  use RentitWeb, :view
end

lib/rentit_web/views/page_view.ex
defmodule RentitWeb.PageView do
  use RentitWeb, :view
end

lib/rentit_web/views/plant_view.ex
defmodule RentitWeb.PlantView do
  use RentitWeb, :view
end

lib/rentit_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Rentit!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/rentit_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/rentit_web/templates/plant/form.html.eex
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

<%= form_for @changeset, @action, fn plant -> %>
  <div class="form-group">
    <%= text_input plant, :name, class: "form-control", id: "name", placeholder: "name" %>
    <%= error_tag plant, :name %>
  </div>

  <div class="form-group">
    <%= text_input plant, :start, class: "form-control", id: "start", placeholder: "start date" %>
    <%= error_tag plant, :start %>
  </div>

  <div class="form-group">
    <%= text_input plant, :end, class: "form-control", id: "end", placeholder: "end date" %>
    <%= error_tag plant, :end %>
  </div>

  <div class="form-group">
    <%= submit "Query plant catalog", id: "submit_button", class: "btn btn-primary" %>
  </div>
<% end %>

lib/rentit_web/templates/plant/index.html.eex
<h1>Enter Rental details</h1>

<%= render "form.html", changeset: @changeset, action: plant_path(@conn, :create) %>

lib/rentit_web/templates/plant/show.html.eex
<h1>Deatils of purchase order (plant rental)</h1>

<ul>

  <li>
    <strong>Plant name:</strong>
    <%= @plant.name %>
  </li>

  <li>
    <strong>Plant Description:</strong>
    <%= @plant.description %>
  </li>

<li>
    <strong>Start Date:</strong>
    <%= @plant.startdate %>
  </li>

  <li>
    <strong>End Date:</strong>
    <%= @plant.enddate %>
  </li>

  <li>
    <strong>Cost:</strong>
    <%= @plant.price %>
  </li>

</ul>

lib/rentit_web/templates/plant/update.html.eex
<h1>List of availale plants</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
<%= for plant <- @plants do %>
    <tr>
      <td><%= plant.name %></td>
      <td><%= plant.description %></td>
      <td><%= plant.price %></td>

      <td >
        <span><%= link "Show", to: plant_path(@conn, :show, plant), class: "btn btn-default btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>